package main

/*
Copyright 2022 Absa Group Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	_ "embed"
	"fmt"
	"os"

	"github.com/AbsaOSS/golic/cmd/commands"
	"github.com/AbsaOSS/golic/cmd/logging"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

//go:embed .golic.yaml
var golicConfig string

func main() {

	var verbose bool

	logging.Init()

	var rootCmd = &cobra.Command{
		Use:   "golic",
		Short: "golic license injector",
		Long:  ``,
		PersistentPreRun: func(cmd *cobra.Command, args []string) {
			logging.LogCommandExecution(cmd, args)
		},
		Run: func(cmd *cobra.Command, args []string) {
			if len(args) == 0 {
				logging.LogShowError("no parameters included")
				_ = cmd.Help()
				os.Exit(0)
			}
		},
		PersistentPostRun: func(cmd *cobra.Command, args []string) {
			os.Exit(0)
		},
	}

	rootCmd.PersistentFlags().BoolVarP(&verbose, "verbose", "v", false, "verbose output")

	rootCmd.AddCommand(commands.VersionCmd)
	rootCmd.AddCommand(commands.InjectCmd)
	rootCmd.AddCommand(commands.RemoveCmd)

	if err := rootCmd.Execute(); err != nil {
		_, err := fmt.Fprintln(os.Stderr, err)
		if err != nil {
			log.Error(err)
		}
		os.Exit(1)
	}
}
