# Copyright 2022 Absa Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
SHELL := bash
ARTIFACT_NAME := golic
TESTPARALLELISM := 4
WORKING_DIR := $(shell pwd)
GOLIC_VERSION  ?= v0.7.2

ifndef NO_COLOR
YELLOW=\033[0;33m
CYAN=\033[1;36m
RED=\033[31m
# no color
NC=\033[0m
endif

.PHONY: clean
clean::
	rm -rf $(WORKING_DIR)/bin

.PHONY: build
build:
	@mkdir -p bin
	go build -o bin/golic main.go

.PHONY: test
test::
	go test -v -tags=all -parallel ${TESTPARALLELISM} -timeout 2h -covermode atomic -coverprofile=covprofile ./...

.PHONY: lint-init
lint-init:
	@echo -e "\n$(CYAN)Check for lint dependencies$(NC)"
	brew install golangci-lint
	brew install gitleaks
	brew install yamllint

.PHONY: lint
lint: test license
	@echo -e "\n$(YELLOW)Running the linters$(NC)"
	@echo -e "\n$(CYAN)golangci-lint$(NC)"
	goimports -w ./
	golangci-lint run
	@echo -e "\n$(CYAN)yamllint$(NC)"
	yamllint .
	@echo -e "\n$(CYAN)gitleaks$(NC)"
	gitleaks detect . --no-git --verbose --config=.gitleaks.toml


.PHONY: license
license:
	@echo -e "\n$(YELLOW)Injecting the license$(NC)"
	./bin/golic inject verbose -c "2022 Absa Group Limited" -t apache2
