package impl

/*
Apache License 2.0

Copyright 2026 Shane & Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import (
	"bytes"
	"io"
	"os"
	"regexp"
	"strings"

	golog "github.com/Bugs5382/go-log"
	"github.com/Bugs5382/golic/internal/logging"
)

// generatedScanLines is how many lines from the top of a file are searched for
// a generated-code marker (#46). Generators write it on the first line or
// just below a build constraint or encoding line.
const generatedScanLines = 10

// generatedScanBytes caps the read, so a minified file with one huge line
// costs no more than this.
const generatedScanBytes = 8 << 10

// generatedMarkers are the markers generators write, in the comment styles of
// the languages golic stamps:
//
//   - Go's convention, "// Code generated <tool>. DO NOT EDIT." (see
//     `go help generate`), written by protoc-gen-go, protoc-gen-go-grpc,
//     protoc-gen-connect-go, stringer, sqlc, controller-gen and others, and
//     used with "#", "--", "/*" and "<!--" by generators for other languages;
//   - protoc's own "Generated by the protocol buffer compiler.  DO NOT EDIT!"
//     (C++, Python, and the gRPC Python plugin's variant);
//   - the "@generated" tag written by protoc-gen-es and other buf plugins.
var generatedMarkers = []*regexp.Regexp{
	regexp.MustCompile(`^(?://|#|--|/\*+|<!--)\s*Code generated .* DO NOT EDIT\b`),
	regexp.MustCompile(`^(?://|#|/\*+)\s*Generated by the .*DO NOT EDIT\b`),
	regexp.MustCompile(`^(?://|#|/\*+)\s*@generated\b`),
}

// generatedMarker returns the marker line when the head of a file says it was
// generated.
func generatedMarker(head []byte) (string, bool) {
	lines := strings.SplitN(string(head), "\n", generatedScanLines+1)
	if len(lines) > generatedScanLines {
		lines = lines[:generatedScanLines]
	}
	for i, l := range lines {
		l = strings.TrimSpace(l)
		for _, re := range generatedMarkers {
			if re.MatchString(l) {
				logging.L().Trace("generated-code marker found", golog.F("line", i+1), golog.F("marker", re.String()))
				return l, true
			}
		}
	}
	return "", false
}

// isGenerated reads the head of the file at path and reports its generated
// marker, if it has one.
func isGenerated(path string) (string, bool, error) {
	f, err := os.Open(path) // #nosec G304 -- path comes from the working-tree walk
	if err != nil {
		logging.L().Debug("opening file for the generated-code check failed", golog.F("path", path), golog.F("error", err.Error()))
		return "", false, err
	}
	defer func() { _ = f.Close() }()

	buf := make([]byte, generatedScanBytes)
	n, err := io.ReadFull(f, buf)
	if err != nil && err != io.EOF && err != io.ErrUnexpectedEOF {
		logging.L().Debug("reading file head for the generated-code check failed", golog.F("path", path), golog.F("error", err.Error()))
		return "", false, err
	}
	marker, ok := generatedMarker(bytes.TrimPrefix(buf[:n], []byte("\xef\xbb\xbf")))
	return marker, ok, nil
}
