package impl

/*
Apache License 2.0

Copyright 2026 Shane & Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The headers below are copied from real generator output.
func TestGeneratedMarkerDetectsGeneratorOutput(t *testing.T) {
	cases := map[string]string{
		"protoc-gen-go":             "// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n// \tprotoc-gen-go v1.36.6\n// \tprotoc        (unknown)\n// source: liveness/v1/liveness.proto\n\npackage livenesspb\n",
		"protoc-gen-go-grpc":        "// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\n// versions:\n// - protoc-gen-go-grpc v1.5.1\n// - protoc             (unknown)\n// source: liveness/v1/liveness.proto\n\npackage livenesspb\n",
		"buf protoc-gen-connect-go": "// Code generated by protoc-gen-connect-go. DO NOT EDIT.\n//\n// Source: foo/v1/foo.proto\n\npackage foov1connect\n",
		"buf protoc-gen-es":         "// @generated by protoc-gen-es v2.2.3 with parameter \"target=ts\"\n// @generated from file foo/v1/foo.proto (package foo.v1, syntax proto3)\n/* eslint-disable */\n\nimport type { GenFile } from \"@bufbuild/protobuf/codegenv1\";\n",
		"protoc python":             "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\n# NO CHECKED-IN PROTOBUF GENCODE\n# source: foo.proto\n# Protobuf Python Version: 5.29.0\n\"\"\"Generated protocol buffer code.\"\"\"\n",
		"protoc grpc python":        "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\n\"\"\"Client and server classes corresponding to protobuf-defined services.\"\"\"\nimport grpc\n",
		"protoc c++":                "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n// NO CHECKED-IN PROTOBUF GENCODE\n// source: foo.proto\n",
		"stringer":                  "// Code generated by \"stringer -type=Color\"; DO NOT EDIT.\n\npackage color\n",
		"controller-gen":            "//go:build !ignore_autogenerated\n\n// Code generated by controller-gen. DO NOT EDIT.\n\npackage v1\n",
		"hash comment":              "# Code generated by a script. DO NOT EDIT.\nkey: value\n",
		"block comment":             "/* Code generated by a tool. DO NOT EDIT. */\nexport const a = 1\n",
		"sql comment":               "-- Code generated by a tool. DO NOT EDIT.\nSELECT 1;\n",
		"crlf":                      "// Code generated by protoc-gen-go. DO NOT EDIT.\r\n\r\npackage x\r\n",
	}
	for name, src := range cases {
		t.Run(name, func(t *testing.T) {
			marker, ok := generatedMarker([]byte(src))
			assert.True(t, ok, "must be detected as generated")
			assert.NotEmpty(t, marker)
			assert.NotContains(t, marker, "\r")
		})
	}
}

func TestGeneratedMarkerIgnoresHandWrittenFiles(t *testing.T) {
	cases := map[string]string{
		"plain go":        plainGo,
		"marker mid line": "// This file is not Code generated by anything. DO NOT EDIT.\npackage x\n",
		"no do not edit":  "// Code generated by hand, feel free to edit.\npackage x\n",
		"string literal":  "package x\n\nconst s = \"// Code generated by x. DO NOT EDIT.\"\n",
		"too far down":    strings.Repeat("// comment\n", generatedScanLines) + "// Code generated by x. DO NOT EDIT.\n",
		"golic header":    "package x\n\n/*\nApache License 2.0\n\nCopyright 2026 Shane & Contributors\n*/\n",
	}
	for name, src := range cases {
		t.Run(name, func(t *testing.T) {
			_, ok := generatedMarker([]byte(src))
			assert.False(t, ok)
		})
	}
}

func TestIsGeneratedReadsOnlyTheHead(t *testing.T) {
	p := filepath.Join(t.TempDir(), "big.pb.go")
	src := "// Code generated by protoc-gen-go. DO NOT EDIT.\n" + strings.Repeat("var _ = 1\n", 100000)
	require.NoError(t, os.WriteFile(p, []byte(src), 0o600))
	marker, ok, err := isGenerated(p)
	require.NoError(t, err)
	assert.True(t, ok)
	assert.Equal(t, "// Code generated by protoc-gen-go. DO NOT EDIT.", marker)
}
