package update

/*
Copyright 2022 Absa Group Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"
)

func TestIsMatch(t *testing.T) {
	tests := []struct {
		name    string
		path    string
		pattern string
		want    bool
	}{
		// Extension matches
		{"ExtMatch", "values.yaml", ".yaml", true},
		{"ExtMismatch", "values.yml", ".yaml", false},

		// Standard wildcards
		{"SingleStarMatch", "service.yaml", "*.yaml", true},
		{"SingleStarDeepMismatch", "templates/service.yaml", "*.yaml", false},

		// Recursive wildcards
		{"RecursiveTemplatesMatch", "charts/templates/service.yaml", "**/templates/**/*.yaml", true},
		{"RecursiveDeepMatch", "charts/sub/templates/nested/pod.yaml", "**/templates/**/*.yaml", true},
		{"RecursiveRootMatch", "templates/pod.yaml", "**/templates/**/*.yaml", true},

		// Question mark wildcards
		{"QuestionMarkMatch", "templates/service.yaml", "template?/service.yaml", true},
		{"QuestionMarkMismatch", "template/service.yaml", "template?/service.yaml", false},
		{"QuestionMarkMulti", "v1.yaml", "v?.yaml", true},

		// General Glob behavior
		{"GlobalYaml", "some/deep/path/config.yaml", "**/*.yaml", true},
		{"GlobalMismatch", "some/deep/path/config.json", "**/*.yaml", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isMatch(tt.path, tt.pattern)
			if got != tt.want {
				t.Errorf("isMatch(%q, %q) = %v; want %v", tt.path, tt.pattern, got, tt.want)
			}
		})
	}
}
