package pkg

/*
Apache License 2.0

Copyright 2022 Absa Group Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"path/filepath"
	"regexp"
	"strings"
)

func IsMatch(s string, p string) bool {
	if strings.HasPrefix(p, ".") {
		return filepath.Ext(s) == p
	}

	var res strings.Builder
	res.WriteString("^")

	i := 0
	for i < len(p) {
		switch {
		// Handle recursive directory prefix: **/
		case i+2 < len(p) && p[i:i+3] == "**/":
			res.WriteString("(?:.*/)?")
			i += 3

		// Handle recursive directory middle: /**/
		case i+3 < len(p) && p[i:i+4] == "/**/":
			res.WriteString("/(?:.*/)?")
			i += 4

		// Handle recursive directory suffix: /**
		case i+2 < len(p) && p[i:i+3] == "/**":
			res.WriteString("(?:/.*)?")
			i += 3

		// Handle single-level wildcard: *
		case p[i] == '*':
			res.WriteString("[^/]*")
			i++

		// Handle single-character wildcard: ?
		case p[i] == '?':
			res.WriteString("[^/]")
			i++

		// Handle literal characters (escape regex meta-chars like . or +)
		default:
			res.WriteString(regexp.QuoteMeta(string(p[i])))
			i++
		}
	}
	res.WriteString("$")

	matched, _ := regexp.MatchString(res.String(), s)
	return matched
}
