name: GoLic
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
jobs:
  GoLic:
    name: GoLic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GoLic
        run: |
          go build -o ./bin/golic main.go
          ./bin/golic inject --dry -c "2022 Absa Group Limited" -t apache2
